# Generated by Django 4.2.7 on 2025-04-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='firma',
            field=models.ImageField(blank=True, help_text='Firma del usuario (formato PNG)', null=True, upload_to='usuarios/firmas/'),
        ),
    ]
