# Generated by Django 4.2.7 on 2025-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_usuario_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True),
        ),
    ]
