# Generated by Django 4.2.7 on 2025-04-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_usuario_cedula_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='contrato_prestamo',
            field=models.FileField(blank=True, null=True, upload_to='contratos_prestamo/'),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='contrato_solicitud',
            field=models.FileField(blank=True, null=True, upload_to='contratos_solicitud/'),
        ),
    ]
