# Generated by Django 4.2.7 on 2025-07-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0013_prestamo_contrato_prestamo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la dependencia', null=True, upload_to='dependencias/'),
        ),
    ]
