# Generated by Django 4.2.7 on 2025-09-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0015_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
