# Generated by Django 4.2.7 on 2025-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0016_notificacion_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('prestamos', models.IntegerField()),
                ('recursos_disponibles', models.IntegerField()),
                ('recursos_prestados', models.IntegerField()),
                ('total_recursos', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
