# Generated by Django 4.2.7 on 2025-09-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0017_estadisticamensual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadisticaMensual',
        ),
    ]
