# Generated by Django 4.2.7 on 2025-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0018_delete_estadisticamensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='id',
            field=models.CharField(help_text='Identificador único asignado manualmente (por ejemplo: DEP001)', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
