# Generated by Django 4.2.7 on 2025-10-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0019_alter_dependencia_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.dependencia')),
            ],
            options={
                'unique_together': {('nombre', 'dependencia')},
            },
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.tiporecurso'),
        ),
    ]
